# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI for New Pull Requests

on:
  pull_request:
    branches:
      - web-map-site

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: npm clean install
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Prettier
        run: npx prettier ./ --check
